DestinationMalgasWebsite/Controllers/BoatingController.cs
using Microsoft.AspNetCore.Mvc;

namespace DestinationMalgasWebsite.Controllers
{
    public class BoatingController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public BoatingController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Boating()
        {
            return View();
        }

        public IActionResult Charters()
        {
            return View();
        }

        public IActionResult Rentals()
        {
            return View();
        }

        public IActionResult BaitAndTackle()
        {
            return View();
        }
    }
}

DestinationMalgasWebsite/Controllers/ContactController.cs
using DestinationMalgasWebsite.BackEndServices.Prog7311_POE_ST10071737.Services;
using Microsoft.AspNetCore.Mvc;

namespace DestinationMalgasWebsite.Controllers
{
    public class ContactController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public ContactController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult ContactUs()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SendEmail(string name, string email, string phoneNumber, string subject, string message)
        {
            var emailService = new EmailService
            {
                name = name,
                email = email,
                phoneNumber = phoneNumber,
                subject = subject,
                body = message
            };

            emailService.CantactpageSender();

            return RedirectToAction("ContactUs");
        }

    }
}

DestinationMalgasWebsite/Controllers/DestinationController.cs
using Microsoft.AspNetCore.Mvc;

namespace DestinationMalgasWebsite.Controllers
{
    public class DestinationController : Controller
    {
        private readonly ILogger<DestinationController> _logger;

        public DestinationController(ILogger<DestinationController> logger)
        {
            _logger = logger;
        }

        public IActionResult Destination()
        {
            return View();
        }

        public IActionResult Malgas()
        {
            return View();
        }

        public IActionResult MalgasFerry()
        {
            return View();
        }

        public IActionResult BoathousePizzaAndPub()
        {
            return View();
        }

        public IActionResult BushPub()
        {
            return View();
        }
        public IActionResult SijnnWineEstate()
        {
            return View();
        }

        public IActionResult Grunters()
        {
            return View();
        }

        public IActionResult DeHoop()
        {
            return View();
        }

        public IActionResult TheFigTree()
        {
            return View();
        }

        public IActionResult Bites()
        {
            return View();
        }

        public IActionResult TheTradingPost()
        {
            return View();
        }
    }
}

DestinationMalgasWebsite/Controllers/MarketingController.cs
using Microsoft.AspNetCore.Mvc;

namespace DestinationMalgasWebsite.Controllers
{
    public class MarketingController : Controller
    {
        private readonly ILogger<MarketingController> _logger;

        public MarketingController(ILogger<MarketingController> logger)
        {
            _logger = logger;
        }

        public IActionResult Marketing()
        {
            return View();
        }

        public IActionResult Website()
        {
            return View();
        }

        public IActionResult SocialMedia()
        {
            return View();
        }

        public IActionResult DirectMarketing()
        {
            return View();
        }
    }
}

DestinationMalgasWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Destination Malgas</title>
</head>
<body>
    <header>
        <nav class="navbar">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/" style="display: flex; align-items: center;">
                        <img id="logo" src="~/Assets/Logo/logoBlackTransparent.svg" alt="Destination Malgas Logo" />
                        <canvas id="color-canvas" style="display: none;"></canvas>
                    </a>
                </div>

                <button class="navbar-toggler" type="button">
                    <img src="~/Assets/Landing/Icon/burgerIcon.svg" alt="Menu" />
                </button>
                <!-- Sidebar Menu -->
                <div class="sidebar">
                    <ul class="sidebar-nav">
                        <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Index">HOME</a></li>
                        <li class="nav-item"><a class="nav-link" asp-controller="Accommodation" asp-action="Accommodation">ACCOMMODATION</a></li>
                        <li class="nav-item"><a class="nav-link" asp-controller="Boating" asp-action="Boating">BOATING</a></li>
                        <li class="nav-item"><a class="nav-link" asp-controller="Marketing" asp-action="Marketing">MARKETING</a></li>
                        <li class="nav-item"><a class="nav-link" asp-controller="Destination" asp-action="Destination">DESTINATION</a></li>
                        <li class="nav-item"><a class="nav-link" asp-controller="Contact" asp-action="ContactUs">CONTACT US</a></li>
                    </ul>
                </div>
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link" asp-controller="Home" asp-action="Index">HOME</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Accommodation" asp-action="Accommodation">ACCOMMODATION</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Boating" asp-action="Boating">BOATING</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Marketing" asp-action="Marketing">MARKETING</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Destination" asp-action="Destination">DESTINATION</a></li>
                    <li class="nav-item"><a class="nav-link" asp-controller="Contact" asp-action="ContactUs">CONTACT US</a></li>
                </ul>
            </div>
        </nav>
    </header>
    <div>
        @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="footer-column left">
            <h3>Our Location</h3>
            <p>
                OFFICE & SHOP:<br>
                PLOT 412, DIEPKLOOF, MALGAS, WC<br>
                Tar Road Diepkloof<br>
                Next to The Boathouse Pub & Pizza, Malgas, WC, 6740
            </p>
        </div>
        <div class="footer-column center">
            <img src="~/Assets/Logo/footer_logo.svg" alt="Footer Logo" class="responsive-image" />
        </div>


        <div class="footer-column right">
            <h3>Contact Us!</h3>
            <div class="contact-info">
                <div class="contact-item">
                    <img src="~/Assets/Footer/Icon/emailIcon.svg" alt="Email Icon" class="contact-icon">
                    <p>
                        <a href="mailto:twan@destinationmalgas.co.za">twan@destinationmalgas.co.za</a><br>
                    </p>
                </div>
                <div class="contact-item">
                    <img src="~/Assets/Footer/Icon/phoneIcon.svg" alt="Phone Icon" class="contact-icon">
                    <p>
                        <a href="https://wa.me/27671629081" target="_blank">+27 (0) 671 629 081</a>
                    </p>
                </div>
            </div>

            <div class="icons-section">
                <img src="~/Assets/Footer/Icon/facebookIcon.svg" alt="Facebook Icon" class="footer-icon">
                <img src="~/Assets/Footer/Icon/instagramIcon.svg" alt="Instagram Icon" class="footer-icon">
                <img src="~/Assets/Footer/Icon/linkedInIcon.svg" alt="LinkedIn Icon" class="footer-icon">
                <img src="~/Assets/Footer/Icon/tiktokIcon.svg" alt="TikTok Icon" class="footer-icon">
                <img src="~/Assets/Footer/Icon/youtubeIcon.svg" alt="YouTube Icon" class="footer-icon">
            </div>

        </div>
    </footer>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/LogoColourChange.js" asp-append-version="true"></script>
</body>
</html>